# Generated by Django 2.2 on 2020-08-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestdepartures',
            name='destination',
            field=models.CharField(default='BSH', max_length=3),
            preserve_default=False,
        ),
    ]
