# Generated by Django 2.2 on 2020-08-03 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_latestdepartures_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departuretime', models.DateTimeField()),
                ('arivaltime', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='latestdepartures',
            name='services',
        ),
        migrations.AddField(
            model_name='latestdepartures',
            name='servicelist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trains.Service'),
            preserve_default=False,
        ),
    ]
