# Generated by Django 2.2 on 2020-08-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0004_auto_20200803_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='arivaltime',
            new_name='arrivaltime',
        ),
    ]
