# Generated by Django 2.2 on 2020-08-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0005_auto_20200803_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestdepartures',
            name='earliest',
        ),
    ]
