# Generated by Django 2.2 on 2020-08-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0006_remove_latestdepartures_earliest'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestdepartures',
            name='station_name',
            field=models.CharField(default='the', max_length=255),
            preserve_default=False,
        ),
    ]
