# Generated by Django 2.2 on 2020-08-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0007_latestdepartures_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='arrfriendly',
            field=models.CharField(default='14:00', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='depfriendly',
            field=models.CharField(default='14:00', max_length=5),
            preserve_default=False,
        ),
    ]
