# Generated by Django 2.2 on 2020-08-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0008_auto_20200804_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='eta',
            field=models.CharField(default='1112', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='schedule_status',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
    ]
