# Generated by Django 2.2 on 2020-08-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0009_auto_20200822_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestdepartures',
            name='daterecorded',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
